import { createServerFn } from '@tanstack/react-start'
import { z } from 'zod'
import { requireSupabaseAuth } from '@/integrations/supabase/auth-middleware'
import { materialSubmissionSchema } from './material-schemas'

const applicationSchema=z.object({name:z.string().trim().min(2).max(160),affiliation:z.string().trim().max(200),expertise:z.array(z.string().trim().min(1).max(60)).max(12),websiteUrl:z.string().url().or(z.literal('')),statement:z.string().trim().min(20).max(1200)})
const profileSchema=z.object({affiliation:z.string().trim().max(200),biography:z.string().trim().max(1200),expertise:z.array(z.string().trim().min(1).max(60)).max(12),websiteUrl:z.string().url().or(z.literal('')),imageUrl:z.string().url().or(z.literal(''))})
const reviewSchema=z.object({requestId:z.string().uuid(),decision:z.enum(['approved','rejected']),note:z.string().trim().max(500).default('')}).superRefine((v,c)=>{if(v.decision==='rejected'&&v.note.length<5)c.addIssue({code:'custom',path:['note'],message:'Add a rejection reason'})})
const inviteSchema=z.object({email:z.string().email(),authorId:z.string().uuid()})

async function requireAdmin(context:{supabase:any;userId:string}){const{data}=await context.supabase.rpc('has_role',{_user_id:context.userId,_role:'admin'});if(!data)throw new Error('Forbidden')}
async function educatorAccount(context:{supabase:any;userId:string}){const{data,error}=await context.supabase.from('educator_accounts').select('author_id,material_authors(*)').eq('user_id',context.userId).maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error('Educator access required');return data}

export const applyForEducatorAccess=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(input=>applicationSchema.parse(input)).handler(async({data,context})=>{const{error}=await context.supabase.from('educator_access_requests').insert({user_id:context.userId,requested_name:data.name,affiliation:data.affiliation,expertise:data.expertise,website_url:data.websiteUrl||null,statement:data.statement,status:'pending'});if(error)throw new Error(error.code==='23505'?'You already have an educator application':error.message);return{ok:true}})

export const getEducatorPortal=createServerFn({method:'GET'}).middleware([requireSupabaseAuth]).handler(async({context})=>{const account=await educatorAccount(context);const authorId=account.author_id;const{data:materials,error}=await context.supabase.from('materials').select('*,subjects(name)').eq('author_id',authorId).order('submitted_at',{ascending:false});if(error)throw new Error(error.message);const list=materials??[];const ids=list.map((m:{id:string})=>m.id);const[sharesResult,requestsResult]=await Promise.all([ids.length?context.supabase.from('study_group_resources').select('group_id,material_id,shared_at,study_groups(name,subjects(name))').in('material_id',ids):Promise.resolve({data:[]}),ids.length?context.supabase.from('material_edit_requests').select('*').in('material_id',ids).order('created_at',{ascending:false}):Promise.resolve({data:[]})]);const titles=new Map(list.map((m:{id:string;title:string})=>[m.id,m.title]));const groups=new Map<string,{groupId:string;name:string;subject:string;shares:number;lastShared:string;materials:string[]}>();for(const share of (sharesResult.data??[]) as any[]){const key=share.group_id;const entry=groups.get(key)??{groupId:key,name:share.study_groups?.name??'Study group',subject:share.study_groups?.subjects?.name??'',shares:0,lastShared:share.shared_at,materials:[]};entry.shares+=1;if(share.shared_at>entry.lastShared)entry.lastShared=share.shared_at;const title=titles.get(share.material_id);if(title&&!entry.materials.includes(title))entry.materials.push(title);groups.set(key,entry)}const approved=list.filter((m:{approval_status:string})=>m.approval_status==='approved');const topViewed=[...approved].sort((a:{view_count:number},b:{view_count:number})=>b.view_count-a.view_count).slice(0,5);return{author:account.material_authors,materials:list,approved,topViewed,groupActivity:[...groups.values()].sort((a,b)=>b.shares-a.shares),editRequests:(requestsResult.data??[]).map((row:any)=>({...row,material_title:titles.get(row.material_id)??''}))}})

const editRequestSchema=z.object({materialId:z.string().uuid(),message:z.string().trim().min(10).max(1000),proposedTitle:z.string().trim().max(160).default(''),proposedDescription:z.string().trim().max(1200).default(''),proposedUrl:z.string().url().or(z.literal('')).default('')})
const editResolveSchema=z.object({requestId:z.string().uuid(),decision:z.enum(['applied','declined']),note:z.string().trim().max(500).default('')})

export const requestMaterialEdit=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(input=>editRequestSchema.parse(input)).handler(async({data,context})=>{const account=await educatorAccount(context);const{data:material,error}=await context.supabase.from('materials').select('id,author_id').eq('id',data.materialId).maybeSingle();if(error)throw new Error(error.message);if(!material||material.author_id!==account.author_id)throw new Error('You can only request edits on your own materials');const{error:insertError}=await context.supabase.from('material_edit_requests').insert({material_id:data.materialId,requested_by:context.userId,message:data.message,proposed_title:data.proposedTitle||null,proposed_description:data.proposedDescription||null,proposed_url:data.proposedUrl||null});if(insertError)throw new Error(insertError.message);return{ok:true}})

export const listMaterialEditRequests=createServerFn({method:'GET'}).middleware([requireSupabaseAuth]).handler(async({context})=>{await requireAdmin(context);const{data,error}=await context.supabase.from('material_edit_requests').select('*,materials(id,title,author_id,material_authors(name))').order('created_at',{ascending:false});if(error)throw new Error(error.message);return{requests:data??[]}})

export const resolveMaterialEditRequest=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(input=>editResolveSchema.parse(input)).handler(async({data,context})=>{await requireAdmin(context);const{data:request,error}=await context.supabase.from('material_edit_requests').select('*').eq('id',data.requestId).single();if(error)throw new Error(error.message);if(data.decision==='applied'){const patch:Record<string,string>={};if(request.proposed_title)patch['title']=request.proposed_title;if(request.proposed_description)patch['description']=request.proposed_description;if(request.proposed_url)patch['url']=request.proposed_url;if(Object.keys(patch).length){const{error:updateError}=await context.supabase.from('materials').update(patch).eq('id',request.material_id);if(updateError)throw new Error(updateError.message)}}const{error:statusError}=await context.supabase.from('material_edit_requests').update({status:data.decision,admin_note:data.note||null,reviewed_by:context.userId,reviewed_at:new Date().toISOString()}).eq('id',data.requestId);if(statusError)throw new Error(statusError.message);return{ok:true}})

export const updateEducatorProfile=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(input=>profileSchema.parse(input)).handler(async({data,context})=>{const account=await educatorAccount(context);const{error}=await context.supabase.from('material_authors').update({affiliation:data.affiliation,biography:data.biography,expertise:data.expertise,website_url:data.websiteUrl||null,image_url:data.imageUrl||null}).eq('id',account.author_id);if(error)throw new Error(error.message);return{ok:true}})

export const submitEducatorMaterial=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(input=>materialSubmissionSchema.parse(input)).handler(async({data,context})=>{const account=await educatorAccount(context);const{data:row,error}=await context.supabase.from('materials').insert({title:data.title,description:data.description,subject_id:data.subjectId,type:data.type,url:data.url,tags:data.tags,author_id:account.author_id,uploaded_by:context.userId,approval_status:'pending',file_path:data.filePath??null,file_name:data.fileName??null,file_mime_type:data.fileMimeType??null,file_size_bytes:data.fileSizeBytes??null}).select('id').single();if(error)throw new Error(error.message);return{id:row.id}})

export const listEducatorAccess=createServerFn({method:'GET'}).middleware([requireSupabaseAuth]).handler(async({context})=>{await requireAdmin(context);const{data:requests,error}=await context.supabase.from('educator_access_requests').select('*,material_authors(name)').order('created_at',{ascending:false});if(error)throw new Error(error.message);const{data:authors}=await context.supabase.from('material_authors').select('id,name,affiliation').order('name');return{requests:requests??[],authors:authors??[]}})

export const reviewEducatorAccess=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(input=>reviewSchema.parse(input)).handler(async({data,context})=>{await requireAdmin(context);const{data:request,error}=await context.supabase.from('educator_access_requests').select('*').eq('id',data.requestId).single();if(error)throw new Error(error.message);let authorId=request.author_id;if(data.decision==='approved'){if(!authorId){const{data:author,error:authorError}=await context.supabase.from('material_authors').insert({name:request.requested_name,affiliation:request.affiliation,expertise:request.expertise,website_url:request.website_url,biography:request.statement}).select('id').single();if(authorError)throw new Error(authorError.message);authorId=author.id}const{supabaseAdmin}=await import('@/integrations/supabase/client.server');const{error:linkError}=await supabaseAdmin.from('educator_accounts').upsert({user_id:request.user_id,author_id:authorId,linked_by:context.userId});if(linkError)throw new Error(linkError.message);const{error:roleError}=await supabaseAdmin.from('user_roles').insert({user_id:request.user_id,role:'teacher'});if(roleError&&roleError.code!=='23505')throw new Error(roleError.message)}const{error:updateError}=await context.supabase.from('educator_access_requests').update({status:data.decision,author_id:authorId,reviewed_by:context.userId,reviewed_at:new Date().toISOString(),decision_note:data.note||null}).eq('id',data.requestId);if(updateError)throw new Error(updateError.message);return{ok:true}})

export const inviteEducator=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(input=>inviteSchema.parse(input)).handler(async({data,context})=>{await requireAdmin(context);const{supabaseAdmin}=await import('@/integrations/supabase/client.server');const{data:profile,error}=await supabaseAdmin.from('profiles').select('id,name').eq('email',data.email).maybeSingle();if(error||!profile)throw new Error('No registered account matches that email');const{error:linkError}=await supabaseAdmin.from('educator_accounts').upsert({user_id:profile.id,author_id:data.authorId,linked_by:context.userId});if(linkError)throw new Error(linkError.message);const{error:roleError}=await supabaseAdmin.from('user_roles').insert({user_id:profile.id,role:'teacher'});if(roleError&&roleError.code!=='23505')throw new Error(roleError.message);await supabaseAdmin.from('educator_access_requests').upsert({user_id:profile.id,author_id:data.authorId,requested_name:profile.name,status:'invited',reviewed_by:context.userId,reviewed_at:new Date().toISOString()},{onConflict:'user_id'});return{ok:true}})
