import { createServerFn } from '@tanstack/react-start'
import { z } from 'zod'
import { requireSupabaseAuth } from '@/integrations/supabase/auth-middleware'
import { materialSubmissionSchema } from './material-schemas'

const applicationSchema=z.object({name:z.string().trim().min(2).max(160),affiliation:z.string().trim().max(200),expertise:z.array(z.string().trim().min(1).max(60)).max(12),websiteUrl:z.string().url().or(z.literal('')),statement:z.string().trim().min(20).max(1200)})
const profileSchema=z.object({affiliation:z.string().trim().max(200),biography:z.string().trim().max(1200),expertise:z.array(z.string().trim().min(1).max(60)).max(12),websiteUrl:z.string().url().or(z.literal('')),imageUrl:z.string().url().or(z.literal(''))})
const reviewSchema=z.object({requestId:z.string().uuid(),decision:z.enum(['approved','rejected']),note:z.string().trim().max(500).default('')}).superRefine((v,c)=>{if(v.decision==='rejected'&&v.note.length<5)c.addIssue({code:'custom',path:['note'],message:'Add a rejection reason'})})
const inviteSchema=z.object({email:z.string().email(),authorId:z.string().uuid()})

async function requireAdmin(context:{supabase:any;userId:string}){const{data}=await context.supabase.rpc('has_role',{_user_id:context.userId,_role:'admin'});if(!data)throw new Error('Forbidden')}
async function educatorAccount(context:{supabase:any;userId:string}){const{data,error}=await context.supabase.from('educator_accounts').select('author_id,material_authors(*)').eq('user_id',context.userId).maybeSingle();if(error)throw new Error(error.message);if(!data)throw new Error('Educator access required');return data}

export const applyForEducatorAccess=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(input=>applicationSchema.parse(input)).handler(async({data,context})=>{const{error}=await context.supabase.from('educator_access_requests').insert({user_id:context.userId,requested_name:data.name,affiliation:data.affiliation,expertise:data.expertise,website_url:data.websiteUrl||null,statement:data.statement,status:'pending'});if(error)throw new Error(error.code==='23505'?'You already have an educator application':error.message);return{ok:true}})

export const getEducatorPortal=createServerFn({method:'GET'}).middleware([requireSupabaseAuth]).handler(async({context})=>{const account=await educatorAccount(context);const authorId=account.author_id;const{data:materials,error}=await context.supabase.from('materials').select('*,subjects(name)').eq('author_id',authorId).order('submitted_at',{ascending:false});if(error)throw new Error(error.message);return{author:account.material_authors,materials:materials??[]}})

export const updateEducatorProfile=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(input=>profileSchema.parse(input)).handler(async({data,context})=>{const account=await educatorAccount(context);const{error}=await context.supabase.from('material_authors').update({affiliation:data.affiliation,biography:data.biography,expertise:data.expertise,website_url:data.websiteUrl||null,image_url:data.imageUrl||null}).eq('id',account.author_id);if(error)throw new Error(error.message);return{ok:true}})

export const submitEducatorMaterial=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(input=>materialSubmissionSchema.parse({...input,authorId:null})).handler(async({data,context})=>{const account=await educatorAccount(context);const{data:row,error}=await context.supabase.from('materials').insert({title:data.title,description:data.description,subject_id:data.subjectId,type:data.type,url:data.url,tags:data.tags,author_id:account.author_id,uploaded_by:context.userId,approval_status:'pending',file_path:data.filePath??null,file_name:data.fileName??null,file_mime_type:data.fileMimeType??null,file_size_bytes:data.fileSizeBytes??null}).select('id').single();if(error)throw new Error(error.message);return{id:row.id}})

export const listEducatorAccess=createServerFn({method:'GET'}).middleware([requireSupabaseAuth]).handler(async({context})=>{await requireAdmin(context);const{data:requests,error}=await context.supabase.from('educator_access_requests').select('*,material_authors(name)').order('created_at',{ascending:false});if(error)throw new Error(error.message);const{data:authors}=await context.supabase.from('material_authors').select('id,name,affiliation').order('name');return{requests:requests??[],authors:authors??[]}})

export const reviewEducatorAccess=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(input=>reviewSchema.parse(input)).handler(async({data,context})=>{await requireAdmin(context);const{data:request,error}=await context.supabase.from('educator_access_requests').select('*').eq('id',data.requestId).single();if(error)throw new Error(error.message);let authorId=request.author_id;if(data.decision==='approved'){if(!authorId){const{data:author,error:authorError}=await context.supabase.from('material_authors').insert({name:request.requested_name,affiliation:request.affiliation,expertise:request.expertise,website_url:request.website_url,biography:request.statement}).select('id').single();if(authorError)throw new Error(authorError.message);authorId=author.id}const{supabaseAdmin}=await import('@/integrations/supabase/client.server');const{error:linkError}=await supabaseAdmin.from('educator_accounts').upsert({user_id:request.user_id,author_id:authorId,linked_by:context.userId});if(linkError)throw new Error(linkError.message);const{error:roleError}=await supabaseAdmin.from('user_roles').insert({user_id:request.user_id,role:'teacher'});if(roleError&&roleError.code!=='23505')throw new Error(roleError.message)}const{error:updateError}=await context.supabase.from('educator_access_requests').update({status:data.decision,author_id:authorId,reviewed_by:context.userId,reviewed_at:new Date().toISOString(),decision_note:data.note||null}).eq('id',data.requestId);if(updateError)throw new Error(updateError.message);return{ok:true}})

export const inviteEducator=createServerFn({method:'POST'}).middleware([requireSupabaseAuth]).inputValidator(input=>inviteSchema.parse(input)).handler(async({data,context})=>{await requireAdmin(context);const{supabaseAdmin}=await import('@/integrations/supabase/client.server');const{data:profile,error}=await supabaseAdmin.from('profiles').select('id,name').eq('email',data.email).maybeSingle();if(error||!profile)throw new Error('No registered account matches that email');const{error:linkError}=await supabaseAdmin.from('educator_accounts').upsert({user_id:profile.id,author_id:data.authorId,linked_by:context.userId});if(linkError)throw new Error(linkError.message);const{error:roleError}=await supabaseAdmin.from('user_roles').insert({user_id:profile.id,role:'teacher'});if(roleError&&roleError.code!=='23505')throw new Error(roleError.message);await supabaseAdmin.from('educator_access_requests').upsert({user_id:profile.id,author_id:data.authorId,requested_name:profile.name,status:'invited',reviewed_by:context.userId,reviewed_at:new Date().toISOString()},{onConflict:'user_id'});return{ok:true}})
