import { createFileRoute,Link } from '@tanstack/react-router'
import { useState } from 'react'
import { useServerFn } from '@tanstack/react-start'
import { GraduationCap,Send } from 'lucide-react'
import { toast } from 'sonner'
import { applyForEducatorAccess } from '@/lib/educators.functions'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
export const Route=createFileRoute('/_authenticated/educator/apply')({head:()=>({meta:[{title:'Apply as an educator | StudyFlow AI'},{name:'description',content:'Request a verified StudyFlow educator profile.'},{property:'og:title',content:'Educator application | StudyFlow AI'},{property:'og:description',content:'Apply to contribute verified teaching resources.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Apply})
function Apply(){const apply=useServerFn(applyForEducatorAccess);const[done,setDone]=useState(false);const[busy,setBusy]=useState(false);const[form,setForm]=useState({name:'',affiliation:'',expertise:'',websiteUrl:'',statement:''});async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{await apply({data:{...form,expertise:form.expertise.split(',').map(x=>x.trim()).filter(Boolean)}});setDone(true);toast.success('Application sent for administrator review')}catch(error){toast.error(error instanceof Error?error.message:'Could not submit application')}finally{setBusy(false)}}if(done)return <div className="page-wrap narrow"><div className="empty-state"><GraduationCap/><h1>Application received</h1><p>An administrator will verify your educator details before granting portal access.</p><Link to="/dashboard"><Button>Return to dashboard</Button></Link></div></div>;return <div className="page-wrap narrow"><div className="page-title"><p className="eyebrow"><GraduationCap/> Educator verification</p><h1>Apply for educator access</h1><p>Tell administrators about your teaching background and expertise.</p></div><form className="onboarding-form" onSubmit={submit}><div><Label htmlFor="teacher-name">Professional name</Label><Input id="teacher-name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><div><Label htmlFor="teacher-affiliation">Institution or affiliation</Label><Input id="teacher-affiliation" value={form.affiliation} onChange={e=>setForm({...form,affiliation:e.target.value})}/></div><div><Label htmlFor="teacher-expertise">Expertise</Label><Input id="teacher-expertise" placeholder="Machine learning, statistics" value={form.expertise} onChange={e=>setForm({...form,expertise:e.target.value})}/></div><div><Label htmlFor="teacher-website">Professional website</Label><Input id="teacher-website" type="url" value={form.websiteUrl} onChange={e=>setForm({...form,websiteUrl:e.target.value})}/></div><div><Label htmlFor="teacher-statement">Teaching background</Label><Textarea id="teacher-statement" value={form.statement} onChange={e=>setForm({...form,statement:e.target.value})} minLength={20} required/></div><Button disabled={busy}><Send/>{busy?'Sending…':'Submit application'}</Button></form></div>}
